version: '3.1'
services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    restart: always

  odoo16:
    image: odoo:16
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    volumes:
      - ./addons:/mnt/extra-addons
    restart: always
